Added feature: Add caching using query parameter
himanshusingh2407/murmur pull request #32
Opened 2019-03-13 20:58 UTC by rgabs

2019-03-14 20:09 UTC, himanshusingh2407 requested changes

2019-03-14 20:09 UTC, himanshusingh2407 commented on app/scripts/urlHandler.js
> +})();
Please add an empty line at the end of this file as followed in `audioScript.js` and `main.js`.

```suggestion
})();

```

2019-03-14 20:09 UTC, himanshusingh2407 commented on app/scripts/urlHandler.js
> +    function resetItems() {
`resetItems` is exposed but not used anywhere.

2019-03-14 20:09 UTC, himanshusingh2407 commented on app/index.html
> +      <a class="menu-option" href="/">
`href="/"` will always reload the page. We can do `onclick="pauseAll()"` instead to pause all.

2019-03-14 20:11 UTC, himanshusingh2407 commented
Thanks @rgabs for taking the time to build this feature. 
👏🏻

2019-03-15 10:05 UTC, rgabs commented on app/scripts/urlHandler.js
> +})();
why is that required though?

2019-03-15 21:27 UTC, merged